openapi: 3.1.0
info:
  title: Prompt API
  description: API to retrieve chat prompts for Financial Planning Expert.
  version: 1.0.0
servers:
  - url: https://bossaert.github.io/prompt-api-schema
    description: GitHub Pages Server
paths:
  /openapi-schema.json:
    get:
      operationId: getPrompts
      summary: Retrieve chat prompts
      responses:
        '200':
          description: A JSON array of chat prompts
          content:
            application/json:
              schema:
                type: object
                properties:
                  prompts:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        prompt:
                          type: string
